# Generated by Django 3.2.11 on 2022-01-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
